Anonymous autograder
kspar/easy pull request #1
Opened 2022-10-11 08:02 UTC by PriitPaluoja

[EZ-1123](https://easy.myjetbrains.com/youtrack/issue/EZ-1123/Anonymous-autograding)
[EZ-1474](https://easy.myjetbrains.com/youtrack/issue/EZ-1474/Anonymous-exercise-get-exercise-details-service)
[EZ-1475](https://easy.myjetbrains.com/youtrack/issue/EZ-1475/Anonymous-autoassess-service)
[EZ-1481](https://easy.myjetbrains.com/youtrack/issue/EZ-1481/Get-exercise-details-service-should-return-new-attrs-related-to-anon-autograde)
[EZ-1482](https://easy.myjetbrains.com/youtrack/issue/EZ-1482/Get-anonymous-submissions-for-exercise-service)
[EZ-1483](https://easy.myjetbrains.com/youtrack/issue/EZ-1483/Update-exercise-service-should-allow-updating-anonymousautoassessenabled)

2022-10-11 12:22 UTC, kspar commented on core/src/main/kotlin/core/ems/service/exercise/AnonymousSubmit.kt
> +                }.lastOrNull()
This cannot actually be null since at least one submission just got inserted.

2022-10-11 12:55 UTC, kspar requested changes

2022-10-11 12:55 UTC, kspar commented on core/src/main/kotlin/core/ems/service/exercise/TeacherReadAnonymousSubmissions.kt
> +        Resp(AnonymousSubmission.slice(
No slice required here?

2022-10-11 12:55 UTC, kspar commented on core/src/main/kotlin/core/ems/service/exercise/AnonymousSubmit.kt
> +private fun selectAutoExIdOrIllegalStateException(exerciseId: Long): Long = transaction {
Why outside of controller?

2022-10-11 13:08 UTC, kspar commented on core/src/main/kotlin/core/ems/service/exercise/AnonymousSubmit.kt
> +        CoroutineScope(EmptyCoroutineContext).launch {
Make sure this works async

2022-10-13 04:45 UTC, PriitPaluoja commented on core/src/main/kotlin/core/ems/service/exercise/TeacherReadAnonymousSubmissions.kt
> +        Resp(AnonymousSubmission.slice(
Yes, not needed. Removed slice

2022-10-13 04:45 UTC, PriitPaluoja commented on core/src/main/kotlin/core/ems/service/exercise/AnonymousSubmit.kt
> +                }.lastOrNull()
True... Changed to last() and removed null check.

2022-10-13 04:46 UTC, PriitPaluoja commented on core/src/main/kotlin/core/ems/service/exercise/AnonymousSubmit.kt
> +private fun selectAutoExIdOrIllegalStateException(exerciseId: Long): Long = transaction {
Now is inside.

2022-10-14 06:58 UTC, merged